Add kover project

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -17,6 +17,7 @@ jobs:
     permissions:
       contents: read
       checks: write
+      pull-requests: write
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -27,12 +28,23 @@ jobs:
           java-version: '${{ env.JDK_VERSION }}'
           cache: 'gradle'
       - name: Build and Run Tests
-        run: ./gradlew test
+        run: ./gradlew test koverXmlReport
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: '**/build/test-results/test/TEST-*.xml'
+      - name: Publish Kover Report
+        uses: madrapps/jacoco-report@v1.6.1
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          paths: |
+            ${{ github.workspace }}/build/reports/kover/report.xml
+          token: ${{ secrets.GITHUB_TOKEN }}
+          min-coverage-overall: 50
+          min-coverage-changed-files: 60
+      - name: Coverage verify
+        run: ./gradlew koverVerify
   detekt:
     name: Detekt
     runs-on: ubuntu-latest
@@ -59,34 +71,3 @@ jobs:
         if: success() || failure() # always run even if the previous step fails
         with:
           path: 'build/reports/detekt/merge.xml'
-  coverage:
-    name: Coverage
-    runs-on: ubuntu-latest
-    permissions:
-      # required for all workflows
-      pull-requests: write
-      # only required for workflows in private repositories
-      actions: read
-      contents: read
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
-      - name: Set up JDK ${{ env.JDK_VERSION }}
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'adopt'
-          java-version: '${{ env.JDK_VERSION }}'
-          cache: 'gradle'
-      - name: Run Kover
-        run: ./gradlew koverXmlReport
-      - name: Publish Kover Report
-        uses: madrapps/jacoco-report@v1.6.1
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          paths: |
-            ${{ github.workspace }}/build/reports/kover/report.xml
-          token: ${{ secrets.GITHUB_TOKEN }}
-          min-coverage-overall: 50
-          min-coverage-changed-files: 60
-      - name: Run Kover Verify
-        run: ./gradlew koverVerify
