Improve codecov reports (#110)

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -20,9 +20,13 @@ jobs:
     runs-on: ubuntu-24.04-arm
     permissions:
       contents: read
-      checks: write
       pull-requests: write
       packages: write
+      # required for all workflows
+      security-events: write
+      checks: write
+      # only required for workflows in private repositories
+      actions: read
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -32,6 +36,13 @@ jobs:
           distribution: 'corretto'
           java-version: '${{ env.JDK_VERSION }}'
           cache: 'gradle'
+      - name: Run Detekt
+        run: ./gradlew detekt
+      - name: Publish Detekt Report
+        uses: jwgmeligmeyling/checkstyle-github-action@master
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          path: 'build/reports/detekt/merge.xml'
       - name: Build and Run Tests
         run: ./gradlew test koverXmlReport --parallel
       - name: Publish Test Report
@@ -43,11 +54,13 @@ jobs:
         uses: codecov/codecov-action@v5
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
+          os: linux-arm64
       - name: Upload test results to Codecov
         if: ${{ !cancelled() }}
         uses: codecov/test-results-action@v1
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
+          os: linux-arm64
       - name: Publish Kover Report
         uses: madrapps/jacoco-report@v1.7.1
         if: success() || failure() # always run even if the previous step fails
@@ -57,38 +70,3 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           min-coverage-overall: 50
           min-coverage-changed-files: 60
-      - name: Coverage verify
-        run: ./gradlew koverVerify --parallel
-      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
-      # the publishing section of your build.gradle
-#      - name: Publish client to GitHub Packages
-#        run: ./gradlew devSnapshot printDevSnapshotReleaseNote
-#        env:
-#          GITHUB_ACTOR: ${{ github.actor }}
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  detekt:
-    name: Detekt
-    runs-on: ubuntu-latest
-    permissions:
-      # required for all workflows
-      security-events: write
-      checks: write
-      # only required for workflows in private repositories
-      actions: read
-      contents: read
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
-      - name: Set up JDK ${{ env.JDK_VERSION }}
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'adopt'
-          java-version: '${{ env.JDK_VERSION }}'
-          cache: 'gradle'
-      - name: Run Detekt
-        run: ./gradlew detekt
-      - name: Publish Detekt Report
-        uses: jwgmeligmeyling/checkstyle-github-action@master
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          path: 'build/reports/detekt/merge.xml'
