Add kover and gh action for coverage (#2)
* Add kover and gh action for coverage

* Add simple test for tracing interceptor

* Migrate to libs.versions.toml

* Add maven central

* Exclude some projects

* Add kover project

* Add tests for kotlet.json

* Add tests for kotlet.metrics

* Add tests for kotlet.metrics

* Add tests for kotlet.tracing

* Fix detekt

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -4,6 +4,7 @@ on:
 
 env:
   JDK_VERSION: 21
+  GRADLE_OPTS: -Dorg.gradle.daemon=false
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
@@ -16,8 +17,7 @@ jobs:
     permissions:
       contents: read
       checks: write
-    env:
-      GRADLE_OPTS: -Dorg.gradle.daemon=false
+      pull-requests: write
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -28,12 +28,23 @@ jobs:
           java-version: '${{ env.JDK_VERSION }}'
           cache: 'gradle'
       - name: Build and Run Tests
-        run: ./gradlew test
+        run: ./gradlew test koverXmlReport
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: '**/build/test-results/test/TEST-*.xml'
+      - name: Publish Kover Report
+        uses: madrapps/jacoco-report@v1.6.1
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          paths: |
+            ${{ github.workspace }}/build/reports/kover/report.xml
+          token: ${{ secrets.GITHUB_TOKEN }}
+          min-coverage-overall: 50
+          min-coverage-changed-files: 60
+      - name: Coverage verify
+        run: ./gradlew koverVerify
   detekt:
     name: Detekt
     runs-on: ubuntu-latest
@@ -44,8 +55,6 @@ jobs:
       # only required for workflows in private repositories
       actions: read
       contents: read
-    env:
-      GRADLE_OPTS: -Dorg.gradle.daemon=false
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
